USE SQL_QUESTIONS;
CREATE TABLE DRUGS(
	DRUG_ID INT,
    DRUG_NAME VARCHAR(50),
    DRUG_TYPE CHAR(5)
);

CREATE TABLE SALES(
	SALE_ID INT,
    DRUG_ID INT,
    SALE_DATE VARCHAR(30),
    UNITS_SOLD INT
);

INSERT INTO DRUGS VALUES
(1, "DrugA", "Type1"),
(2, "DrugB", "Type2"),
(3, "DrugC", "Type3"),
(4, "DrugD", "Type1"), 
(5, "DrugE", "Type2");

INSERT INTO SALES VALUES
(101, 1, "06/08/2022 00:00:00", 100),
(102, 1, "06/10/2022 00:00:00", 150),
(103, 2, "06/18/2022 00:00:00", 200),
(104, 2, "07/26/2022 00:00:00", 250),
(105, 3, "07/05/2022 00:00:00", 150);

ALTER TABLE SALES
ADD COLUMN CONVERTED_DATETIME DATETIME;

UPDATE SALES
SET CONVERTED_DATETIME = STR_TO_DATE(SALE_DATE, "%m/%d/%Y %H:%i:%s")
WHERE SALES.CONVERTED_DATETIME IS NULL;

WITH MONTHLY_SALES AS(
	SELECT DRUG_NAME, date_format(STR_TO_DATE(SALE_DATE, "%m/%d/%Y %H:%i:%s"), "%Y-%m-%01 %H:%i:%s") AS SALE_MONTH, SUM(UNITS_SOLD) AS MONTHLY_SALES
	FROM 
	DRUGS JOIN SALES	
	ON SALES.DRUG_ID = DRUGS.DRUG_ID
	GROUP BY DRUG_NAME, SALE_MONTH
)

SELECT DRUG_NAME, SALE_MONTH, MONTHLY_SALES, 
SUM(MONTHLY_SALES) OVER(PARTITION BY DRUG_NAME ORDER BY SALE_MONTH) AS CUMULATIVE_SALES
FROM MONTHLY_SALES;

SELECT CONVERTED_DATETIME FROM SALES;

SET SQL_SAFE_UPDATES = 0;
