USE SQL_QUESTIONS;

CREATE TABLE PRODUCT_INFO(
	PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(50),
    PRODUCT_LINE VARCHAR(20)
);

CREATE TABLE TRANSACTIONS(
	TRANSACTION_ID INT,
    PRODUCT_ID INT,
    AMOUNT INT
);

INSERT INTO PRODUCT_INFO
VALUES
(1, "Quadro-RTX 8000", "),