CREATE DATABASE Employee_db;
USE EMPLOYEE_DB;

CREATE TABLE EMPLOYEE_SALES_TABLE(
	ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    REGION VARCHAR(20),
    NUM_OF_SALES INT
);

INSERT INTO EMPLOYEE_SALES_TABLE
VALUES
(1, "ADAM", "CALIFORNIA", 120),
(2, "DRISHTI", "MUMBAI", 130),
(3, "SURAJ", "DELHI", 140),
(4, "DRONA", "GUJRAT", 140);

SELECT NAME, REGION, NUM_OF_SALES,
ROW_NUMBER() OVER(PARTITION BY REGION ORDER BY NUM_OF_SALES DESC) AS ROW_NUM,
RANK() OVER(PARTITION BY REGION ORDER BY NUM_OF_SALES DESC) AS RANKING,
DENSE_RANK() OVER(PARTITION BY REGION ORDER BY NUM_OF_SALES DESC) AS DENSE_RANKING,
PERCENT_RANK() OVER(PARTITION BY REGION ORDER BY NUM_OF_SALES DESC) AS PERCENT_RANKING
FROM EMPLOYEE_SALES_TABLE;

UPDATE EMPLOYEE_SALES_TABLE
SET REGION = "CALIFORNIA"
WHERE REGION IN ("DELHI", "GUJRAT", "MUMBAI");

SET SQL_SAFE_UPDATES = 0;

SELECT NAME, REGION, NUM_OF_SALES,
FIRST_VALUE(NUM_OF_SALES) OVER(PARTITION BY REGION ORDER BY NUM_OF_SALES DESC) AS "FIRST_VALUE_PER_REGION",
LAST_VALUE(NUM_OF_SALES) OVER(PARTITION BY REGION ORDER BY NUM_OF_SALES DESC) AS "LAST_VALUE_PER_REGION",
LEAD(NUM_OF_SALES, 2) OVER(PARTITION BY REGION ORDER BY NUM_OF_SALES DESC) AS "LEAD BY 2",
LAG(NUM_OF_SALES, 2) OVER(PARTITION BY REGION ORDER BY NUM_OF_SALES DESC) AS "LAG BY 2"
FROM EMPLOYEE_SALES_TABLE;

CREATE TABLE CUSTOMERS(
	ID INT PRIMARY KEY,
    NAME VARCHAR(50)
);

INSERT INTO CUSTOMERS
VALUES
(1, "ADITYA"),
(2, "RAJ"),
(3, "MOHAN");

CREATE TABLE PRODUCT(
	ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(50)
);

INSERT INTO PRODUCT
VALUES
(1, "HAIR GEL"),
(2, "ATTA"),
(3, "TOOTHBRUSH");

CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    PRODUCT_ID INT
);

INSERT INTO ORDERS
VALUES
(1001, 1, 1),
(1002, 2, 2),
(1003, 3, 3);

SELECT *
FROM CUSTOMERS
JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID
JOIN PRODUCT ON ORDERS.PRODUCT_ID = PRODUCT.ID;